name: Deploy to Heroku

on:
  push:
    branches:
    - master
    - qa

env:
  HEROKU_API_KEY: ${{ '958b05ea-bcd9-4732-9fcb-72cdc8def584' }}
  APP_NAME_PROD: ${{ 'behavior-net' }}
  APP_NAME_QA: ${{ 'behavior-net-qa' }}

jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry (Prod)
    - name: Publish to Prod
      if: endsWith(github.ref, '/master')
      run: |
        heroku container:push web -a $APP_NAME_PROD
        heroku container:release web -a $APP_NAME_PROD

    # Push the Docker image to Heroku Container Registry (QA)
    - name: Publish to QA
      if: endsWith(github.ref, '/qa')
      run: |
        heroku container:push web -a $APP_NAME_QA
        heroku container:release web -a $APP_NAME_QA